version: 2.1
executors:
  tencent-cloud-hk:
    machine: true
    resource_class: mac-mini/server-1
    working_directory: /var/opt/circleci/workdir/StandBy-Web
    shell: /usr/bin/bash
workflows:
  build:
    jobs:
      - clone-or-pull-repo
      - build:
          requires:
            - clone-or-pull-repo
      - deploy:
          requires:
            - build

jobs:
  clone-or-pull-repo:
    executor: tencent-cloud-hk
    working_directory: /var/opt/circleci/workdir
    steps:
      - run:
          name: "Check tools"
          command: |
            echo "Current user: $(whoami)"
            echo "Current dir: $(pwd)"
            echo "Current shell: $SHELL"
            echo "git version: $(git --version)"
      - run:
          name: "Clone or Pull StandBy-Web repo"
          command: |
            if [ -d "StandBy-Web" ] && [ ! -d "StandBy-Web/.git" ]; then
              echo "Error: Directory 'StandBy-Web' exists but is not a Git repository." >&2
              exit 1
            fi
            grep -q github.com ~/.ssh/known_hosts 2>/dev/null || ssh-keyscan -t rsa,ed25519 github.com >> ~/.ssh/known_hosts
            if [ ! -d "StandBy-Web/.git" ]; then
              echo "Cloning repository..."
              git clone git@github.com:Fu-XDU/StandBy-Web.git
            else
              echo "Pulling latest changes..."
              cd StandBy-Web
              git reset --hard
              git clean -fd
              git pull origin main
            fi
  build:
    executor: tencent-cloud-hk
    steps:
      - run:
          name: "Setup Node environment"
          command: |
            cat ~/.profile >> "$BASH_ENV"
            source "$BASH_ENV"
            echo "Current user: $(whoami)"
            echo "Current dir: $(pwd)"
            echo "Current shell: $SHELL"
            echo "Node version: $(node -v)"
            echo "npm version: $(npm -v)"
      - run:
          name: "Install Dependencies"
          command: | 
            npm install
      - run:
          name: "Build Dist"
          command: |
            npm run build
  deploy:
    executor: tencent-cloud-hk
    steps:
      - run:
          name: "Deploy"
          command: |
            rm -rf /var/opt/circleci/artifacts/standby
            mv dist /var/opt/circleci/artifacts/standby