version: 2.1
workflows:
  build:
    jobs:
      - clone-or-pull-repo
      - build:
          requires:
            - clone-or-pull-repo

jobs:
  clone-or-pull-repo:
    machine: true
    resource_class: mac-mini/server-1
    shell: /bin/zsh  # 使用 zsh
    environment:
      https_proxy: http://127.0.0.1:7890
      http_proxy: http://127.0.0.1:7890
      all_proxy: socks5://127.0.0.1:7890
    steps:
      - run:
          name: "Check tools"
          command: |
            source "$BASH_ENV"
            echo "Current shell: $SHELL"
            echo "git version: $(git -v)"
      - run:
          name: "Clone or Pull stand-by-web repo"
          command: |
            mkdir -p ~/CircleCI
            cd ~/CircleCI
            if [ -d "stand-by-web" ] && [ ! -d "stand-by-web/.git" ]; then
              echo "Error: Directory 'stand-by-web' exists but is not a Git repository." >&2
              exit 1
            fi
            if [ ! -d "stand-by-web/.git" ]; then
              echo "Cloning repository..."
              git clone git@github.com:Fu-XDU/StandBy-Web.git
            else
              echo "Pulling latest changes..."
              cd stand-by-web
              git reset --hard
              git clean -fd
              git pull origin main
            fi
  build:
    machine: true
    resource_class: mac-mini/server-1
    shell: /bin/zsh  # 使用 zsh
    steps:
      - run:
          name: "Setup Node environment"
          command: |
            cd ~/CircleCI/stand-by-web
            echo "Current shell: $SHELL"
            cat ~/.zshrc >> "$BASH_ENV"
            source "$BASH_ENV"
            echo "Node version: $(node -v)"
            echo "npm version: $(npm -v)"
      - run:
          name: "Install Dependencies"
          command: | 
            source "$BASH_ENV"
            npm install
      - run:
          name: "Build Dist"
          command: |
            source "$BASH_ENV"
            npm run build
      - run:
          name: "Deploy"
          command: |
            rm -rf /opt/homebrew/var/www/standby
            mv dist /opt/homebrew/var/www/standby